name: Resize Images

on:
  push:
    paths:
      - "fantom/images/**"

jobs:
  resize-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Resize images
        uses: ./.github/actions/image-resizer
        with:
          path: "fantom/images/"
          size: "128x128"
          subfolder_name: "128x128"
      - name: Configure Git
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      - name: Commit resized images
        run: |
          git add fantom/images/128x128/
          git commit -m "Add resized images" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
